
export const SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION"
export const SUCCESSFUL_ERROR = "SUCCESSFUL_ERROR"
export const CLEAR_MESSAGE = "CLEAR_MESSAGE"

export const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN"

export const AUTH_COMPROBATION = "AUTH_COMPROBATION"
export const LOG_OUT = "LOG_OUT"

export const UPLOAD_FILE = "UPLOAD_FILE"
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR"
export const LOADING_TRUE = "LOADING_TRUE"
export const LINK_CREATES_SUCCESSFUL = "LINK_CREATES_SUCCESSFUL"

export const CLEAR_STATE ="CLEAR_STATE"
export const GET_PASSWORD ="GET_PASSWORD"
export const GET_DOWLOADS = "GET_DOWLOADS"